### PR TITLE
Add nodal z variable for particles

### PR DESCRIPTION
**Pull request by jmsexton03**

### CODE REVIEW

**Comment by asalmgren** [comment]
z_phys_nd(i,j,k)=0.5*(z_w(i,j,k)+z_w(i+1,j,k));
This formula isn't right -- we want to average all four z_w values (i,j), (i+1,j), (i,j+1), (i+1,j+1) onto the node

**Comment by asalmgren** [comment]
Also see this error:

https://github.com/seahorce-scidac/docs.git/': The requested URL returned error: 403

**Comment by hklion** [comment]
> Also see this error:
> 
> https://github.com/seahorce-scidac/docs.git/': The requested URL returned error: 403

This is a test configuration thing. I just pushed something to development that should fix this -- we were unconditionally trying to deploy the docs to the website, even on pull requests.

**Comment by jmsexton03** [comment]
> z_phys_nd(i,j,k)=0.5*(z_w(i,j,k)+z_w(i+1,j,k)); This formula isn't right -- we want to average all four z_w values (i,j), (i+1,j), (i,j+1), (i+1,j+1) onto the node

An update which addresses this had been pushed

**Pull request merged**
